# In _config.yml
title: A Practical and Computational Introduction to Mathematical Cryptography
author: Luís Finotti
copyright: "2025"
execute:
  execute_notebooks: force

# repository:
#   url: https://github.com/lrfinotti/cybr201_book

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - ref.bib

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    bibtex_reference_style: author_year
  extra_extensions:
    - sphinx_proof

# parse:
#   myst_enable_extensions:
#     # don't forget to list any other extensions you want enabled,
#     # including those that are enabled by default!
#     - amsmath
